import "../styles/globals.css";
import { Inter } from "next/font/google";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout(props) {
  const {
    children,
    title = "Create Next App",
    description = "Generated by create next app",
  } = props;

  return (
    <html lang="en">
      <head>
        <Header title={title} description={description} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
