"use client";

import "../styles/globals.css";
import { ThemeProvider, useTheme } from "../components/atoms/ThemeContext";

import Header from "../components/molecules/Header";

export default function RootLayout(props) {
  const theme = useTheme();
  const { apiKey, secretKey } = process.env;

  const {
    children,
    title = "Create Next App",
    description = "Generated by create next app",
  } = props;

  return (
    <html lang="en">
      <head>
        <Header title={title} description={description} />
      </head>
      <ThemeProvider>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
