import "../styles/globals.css";
import { ThemeProvider } from "../components/atoms/ThemeContext";
import Header from "../components/molecules/Header";

// This is the server-rendered part
export default function RootLayout({ children }) {
  const isExportMode = process.env.NEXT_PUBLIC_EXPORT_MODE === "true";

  return (
    <html lang="en">
      <head>
        <Header title="Create Next App" description="Generated by create next app" />
      </head>
      <body>
        {/* Wrap the client-side logic in a Client Component */}
        <ClientWrapper isExportMode={isExportMode}>{children}</ClientWrapper>
      </body>
    </html>
  );
}

// Move client-side logic to a Client Component
function ClientWrapper({ isExportMode, children }) {
  return (
    <ThemeProvider>
      {isExportMode ? (
        children // Directly render children in export mode
      ) : (
        // Render additional UI in non-export mode
        <div className="app-container">{children}</div>
      )}
    </ThemeProvider>
  );
}
